{
  "openapi": "3.0.0",
  "info": {
    "title": "Application Subscriber API",
    "version": "DEV",
    "description": "API vom Fachverfahren zum Zustelldienst",
    "contact": {
      "name": "FITKO",
      "url": "https://www.fitko.de/"
    },
    "license": {
      "name": "Creative Commons Attribution Share Alike 4.0 (CC BY-SA 4.0)",
      "url": "https://creativecommons.org/licenses/by-sa/4.0/"
    }
  },
  "servers": [
    {
      "url": "https://subscriber.fiep-poc.de/beta5",
      "description": "Produktionsumgebung der API."
    }
  ],
  "paths": {
    "/{subscriberId}/destinations": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "subscriberId",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "List Destinations",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "../models/destination.json"
                  }
                },
                "examples": {
                  "example-1": {
                    "value": [
                      {
                        "destination-id": "83578",
                        "public-organization": {
                          "organizationName": "Gewerbeamt Musterhausen"
                        },
                        "technicalContact": [
                          {
                            "firstName": "Werner",
                            "lastName": "Mustermann",
                            "contact": {
                              "telephone": [
                                {
                                  "number": "+49 89 32168-42",
                                  "mobile": false,
                                  "description": "Dienstliches Festnetz"
                                }
                              ]
                            }
                          }
                        ],
                        "callback": {
                          "callbackURI": "https://www.example.com/callback"
                        }
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          }
        },
        "operationId": "list-destinations",
        "description": "Ruft die Liste aller Destinations dieses Accounts auf.",
        "tags": [
          "Destination Management"
        ],
        "security": [
          {
            "OAuth 2.0": [
              "{subscriberId}:destination:read",
              "{subscriberId}:manage",
              "{subscriberId}:destination:manage"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create Destination",
        "operationId": "create-destination",
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "destinationId": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "destinationId"
                  ]
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "destinationId": "e15fc92e-c286-424b-9802-39c6b6bc441d"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          }
        },
        "description": "Legt eine neue Destination an.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "../models/destination-no-id.json"
              },
              "examples": {
                "example-1": {
                  "value": {
                    "public-organization": {
                      "organizationName": "Gewerbeamt Musterhausen"
                    },
                    "technicalContact": [
                      {
                        "firstName": "Werner",
                        "lastName": "Mustermann",
                        "contact": {
                          "telephone": [
                            {
                              "number": "+49 89 32168-42",
                              "mobile": false,
                              "description": "Dienstliches Festnetz"
                            }
                          ]
                        }
                      }
                    ],
                    "callback": {
                      "callbackURI": "https://www.example.com/callback"
                    }
                  }
                }
              }
            }
          },
          "description": "Anzulegende Destination"
        },
        "tags": [
          "Destination Management"
        ],
        "security": [
          {
            "OAuth 2.0": [
              "{subscriberId}:manage",
              "{subscriberId}:destination:manage",
              "{subscriberId}:destination:create"
            ]
          }
        ]
      }
    },
    "/{subscriberId}/destinations/{destinationId}/applications/{applicationId}/data": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "subscriberId",
          "in": "path",
          "required": true
        },
        {
          "schema": {
            "type": "string"
          },
          "name": "destinationId",
          "in": "path",
          "required": true
        },
        {
          "schema": {
            "type": "string"
          },
          "name": "applicationId",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Get Application Data",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "F99000001": "Eins",
                      "G99000001": {
                        "F99000002": "Zwei",
                        "F99000003": "Drei"
                      }
                    }
                  }
                }
              },
              "application/xml": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {}
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          }
        },
        "operationId": "get-application-data",
        "description": "Ruft die Fachdaten der Application ab.\n\nBeispiele:\n#### JSON\n```json\n{\n    \"F99000001\": \"Eins\",\n    \"G99000001\": {\n        \"F99000002\": \"Zwei\",\n        \"F99000003\": \"Drei\"\n    }\n}\n```\n\n#### XML\n```xml\n<S99000001>\n  <F99000001>Eins</F99000001>\n  <G99000001>\n    <F99000002>Zwei</F99000002>\n    <F99000003>Drei</F99000003>\n  </G99000001>\n</S99000001>\n```",
        "tags": [
          "Application Retrieval"
        ],
        "security": [
          {
            "OAuth 2.0": [
              "{subscriberId}:manage",
              "{subscriberId}:application:receive",
              "{subscriberId}:destination:{destinationId}:application:receive"
            ]
          }
        ]
      }
    },
    "/{subscriberId}/destinations/{destinationId}/applications/{applicationId}/docs/{docId}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "subscriberId",
          "in": "path",
          "required": true
        },
        {
          "schema": {
            "type": "string"
          },
          "name": "destinationId",
          "in": "path",
          "required": true
        },
        {
          "schema": {
            "type": "string"
          },
          "name": "applicationId",
          "in": "path",
          "required": true
        },
        {
          "schema": {
            "type": "string"
          },
          "name": "docId",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Get Application Document",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "string",
                  "format": "binary"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          }
        },
        "operationId": "get-application-document",
        "description": "Ruf ein Dokument (Formular oder Anlage) der Application ab.",
        "tags": [
          "Application Retrieval"
        ],
        "security": [
          {
            "OAuth 2.0": [
              "{subscriberId}:manage",
              "{subscriberId}:application:receive",
              "{subscriberId}:destination:{destinationId}:application:receive"
            ]
          }
        ]
      }
    },
    "/{subscriberId}/destinations/{destinationId}/applications/{applicationId}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "subscriberId",
          "in": "path",
          "required": true
        },
        {
          "schema": {
            "type": "string"
          },
          "name": "destinationId",
          "in": "path",
          "required": true
        },
        {
          "schema": {
            "type": "string"
          },
          "name": "applicationId",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Get Application Metadata",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/application/metadata.json"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "applicationId": "7236",
                      "additionalReferenceInfo": {
                        "subject": "Anmeldung eines Gewerbes in Musterstadt",
                        "caseId": "DF/8923"
                      },
                      "contentStructure": {
                        "data": {
                          "size": 9438,
                          "schema": {
                            "mimeType": "json",
                            "schemaSource": "none"
                          }
                        },
                        "docs": [
                          {
                            "docId": "1",
                            "purpose": "form",
                            "size": 39273,
                            "mimeType": "application/pdf",
                            "filename": "antrag.pdf",
                            "description": "Das Antragsformular",
                            "lang": {
                              "lang": "de",
                              "region": "DE"
                            },
                            "hash": {
                              "algorithm": "SHA-256",
                              "digest": "03ba204e50d126e4674c005e04d82e84c21366780af1f43bd54a37816b6ab340"
                            }
                          },
                          {
                            "docId": "2",
                            "purpose": "attachment",
                            "size": 894834874,
                            "mimeType": "image/jpeg",
                            "filename": "scan.jpg",
                            "description": "Scan der Bescheinigung",
                            "hash": {
                              "algorithm": "SHA-256",
                              "digest": "e1762f14d9924e37b32f1c81dfd256410af462f5136415c96877efa8c80345d0"
                            }
                          }
                        ]
                      },
                      "publicServiceType": {
                        "name": "Gewerbeanmeldung",
                        "description": "Eine Gewerbeanmeldung ist immer dann notwendig, wenn Sie einen stehenden Gewerbebetrieb beginnen.",
                        "leikaId": "99050012104000",
                        "otherIdentifiers": [
                          {
                            "id": "8664844",
                            "schemeURI": "service.niedersachsen.de",
                            "schemeName": "Serviceportal Niedersachsen"
                          },
                          {
                            "id": "354824",
                            "schemeURI": "buerger.thueringen.de",
                            "schemeName": "Zuständigkeitsfinder Thüringen"
                          }
                        ]
                      },
                      "applicants": [
                        {
                          "identifier": [
                            {
                              "id": "918",
                              "schemeName": "Antragsportal",
                              "schemeId": "urn:com:example:antragsportal:user"
                            }
                          ],
                          "contactInfo": {
                            "physicalAddress": {
                              "street": "Kurzer Weg",
                              "houseNumber": 7,
                              "postalCode": "12345",
                              "city": "string",
                              "addressSupplement": "string"
                            },
                            "telephone": [
                              {
                                "number": "+49 89 32168-42",
                                "mobile": true,
                                "description": "string"
                              }
                            ],
                            "electronicAddresses": [
                              {
                                "channelType": "Service-Account-Mailbox",
                                "address": "string"
                              }
                            ]
                          },
                          "identityInfo": {
                            "gender": "m",
                            "nationality": "string",
                            "familyName": "string",
                            "givenName": "string",
                            "birthName": "string",
                            "doctoralDegrees": "string",
                            "artisticName": "string",
                            "dateOfBirth": "2020-04-16",
                            "placeOfBirth": "string",
                            "placeOfResidence": {
                              "street": "string",
                              "houseNumber": null,
                              "houseNumberSuffix": "st",
                              "postalCode": "strin",
                              "city": "string",
                              "addressSupplement": "string"
                            }
                          },
                          "authentificationInfo": {
                            "timestamp": "2020-04-16T06:50:39Z",
                            "authentificationToken": {},
                            "authentificationMethod": "string",
                            "assuranceLevel": "low"
                          }
                        }
                      ],
                      "payment-info": {
                        "reference": "TP/93/GDP",
                        "usage": "Gewerbeanmeldung",
                        "amount": 17.3,
                        "timestamp": "2020-03-03T12:38:23Z",
                        "status": "success",
                        "transaction": "1f77c5f9b759db9cdce59988b24974d465c7be5e462a6185485559ff6e2dea82"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          }
        },
        "operationId": "get-application",
        "description": "Ruft eine wartende Application ab.",
        "tags": [
          "Application Retrieval"
        ],
        "security": [
          {
            "OAuth 2.0": [
              "{subscriberId}:manage",
              "{subscriberId}:application:receive",
              "{subscriberId}:destination:{destinationId}:application:receive"
            ]
          }
        ]
      },
      "post": {
        "summary": "Acknowledge Application",
        "operationId": "ack-application",
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "417": {
            "description": "Expectation Failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          }
        },
        "description": "Bestätigt die Abholung der Application. Über den Parameter `finalDelivery` im Body wird gesteuert, wie der Folgestatus aussieht:\n\n| final-delivery | status      |\n| -------------- | ----------- |\n| `false`        | \"forwarded\" |\n| `true`         | \"delivered\" |\n\nDer Parameter `finalDelivery` zeigt an, ob der Antrag noch weitergesendet wird (`false`) oder das finale Ziel erreicht hat (`true`).\n\nSofern der Wert `false` übergeben wurde, muss zu einem späteren Zeitpunkt, wenn der Antrag final zugestellt wurde, ein weiterer Aufruf mit dem Wert `true` erfolgen.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "finalDelivery": {
                    "type": "boolean",
                    "description": "Zeigt an, ob die Zustellung zum nächsten Hop (`false`) oder bis zum Endpunkt (`true`) erfolgt ist."
                  }
                },
                "required": [
                  "finalDelivery"
                ]
              }
            }
          },
          "description": "Details der Quittung"
        },
        "tags": [
          "Application Retrieval"
        ],
        "security": [
          {
            "OAuth 2.0": [
              "{subscriberId}:manage",
              "{subscriberId}:application:receive",
              "{subscriberId}:destination:{destinationId}:application:receive"
            ]
          }
        ]
      }
    },
    "/{subscriberId}/destinations/{destinationId}/applications": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "subscriberId",
          "in": "path",
          "required": true
        },
        {
          "schema": {
            "type": "string"
          },
          "name": "destinationId",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "List Applications",
        "operationId": "list-applications",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "../models/application/metadata.json"
                  }
                },
                "examples": {
                  "example-1": {
                    "value": []
                  },
                  "example-2": {
                    "value": [
                      {
                        "applicationId": "7236",
                        "additionalReferenceInfo": {
                          "subject": "Anmeldung eines Gewerbes in Musterstadt",
                          "caseId": "DF/8923"
                        },
                        "contentStructure": {
                          "data": {
                            "size": 9438,
                            "schema": {
                              "mimeType": "json",
                              "schemaSource": "none"
                            }
                          },
                          "docs": [
                            {
                              "docId": "1",
                              "purpose": "form",
                              "size": 39273,
                              "mimeType": "application/pdf",
                              "filename": "antrag.pdf",
                              "description": "Das Antragsformular",
                              "lang": {
                                "lang": "de",
                                "region": "DE"
                              },
                              "hash": {
                                "algorithm": "SHA-256",
                                "digest": "03ba204e50d126e4674c005e04d82e84c21366780af1f43bd54a37816b6ab340"
                              }
                            },
                            {
                              "docId": "2",
                              "purpose": "attachment",
                              "size": 894834874,
                              "mimeType": "image/jpeg",
                              "filename": "scan.jpg",
                              "description": "Scan der Bescheinigung",
                              "hash": {
                                "algorithm": "SHA-256",
                                "digest": "e1762f14d9924e37b32f1c81dfd256410af462f5136415c96877efa8c80345d0"
                              }
                            }
                          ]
                        },
                        "publicServiceType": {
                          "name": "Gewerbeanmeldung",
                          "description": "Eine Gewerbeanmeldung ist immer dann notwendig, wenn Sie einen stehenden Gewerbebetrieb beginnen.",
                          "leikaId": "99050012104000",
                          "otherIdentifiers": [
                            {
                              "id": "8664844",
                              "schemeURI": "service.niedersachsen.de",
                              "schemeName": "Serviceportal Niedersachsen"
                            },
                            {
                              "id": "354824",
                              "schemeURI": "buerger.thueringen.de",
                              "schemeName": "Zuständigkeitsfinder Thüringen"
                            }
                          ]
                        },
                        "applicants": [
                          {
                            "identifier": [
                              {
                                "id": "918",
                                "schemeName": "Antragsportal",
                                "schemeId": "urn:com:example:antragsportal:user"
                              }
                            ],
                            "contactInfo": {
                              "physicalAddress": {
                                "street": "Kurzer Weg",
                                "houseNumber": 7,
                                "postalCode": "12345",
                                "city": "string",
                                "addressSupplement": "string"
                              },
                              "telephone": [
                                {
                                  "number": "+49 89 32168-42",
                                  "mobile": true,
                                  "description": "string"
                                }
                              ],
                              "electronicAddresses": [
                                {
                                  "channelType": "Service-Account-Mailbox",
                                  "address": "string"
                                }
                              ]
                            },
                            "identityInfo": {
                              "gender": "m",
                              "nationality": "string",
                              "familyName": "string",
                              "givenName": "string",
                              "birthName": "string",
                              "doctoralDegrees": "string",
                              "artisticName": "string",
                              "dateOfBirth": "2020-04-16",
                              "placeOfBirth": "string",
                              "placeOfResidence": {
                                "street": "string",
                                "houseNumber": null,
                                "houseNumberSuffix": "st",
                                "postalCode": "strin",
                                "city": "string",
                                "addressSupplement": "string"
                              }
                            },
                            "authentificationInfo": {
                              "timestamp": "2020-04-16T06:50:39Z",
                              "authentificationToken": {},
                              "authentificationMethod": "string",
                              "assuranceLevel": "low"
                            }
                          }
                        ],
                        "payment-info": {
                          "reference": "TP/93/GDP",
                          "usage": "Gewerbeanmeldung",
                          "amount": 17.3,
                          "timestamp": "2020-03-03T12:38:23Z",
                          "status": "success",
                          "transaction": "1f77c5f9b759db9cdce59988b24974d465c7be5e462a6185485559ff6e2dea82"
                        }
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          }
        },
        "description": "Ruft die Liste der wartenden Applications ab.",
        "tags": [
          "Application Retrieval"
        ],
        "security": [
          {
            "OAuth 2.0": [
              "{subscriberId}:manage",
              "{subscriberId}:application:receive",
              "{subscriberId}:destination:{destinationId}:application:receive"
            ]
          }
        ]
      }
    },
    "/{subscriberId}/destinations/{destinationId}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "destinationId",
          "in": "path",
          "required": true
        },
        {
          "schema": {
            "type": "string"
          },
          "name": "subscriberId",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Get Destination",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/destination.json"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "destination-id": "83578",
                      "public-organization": {
                        "organizationName": "Gewerbeamt Musterhausen"
                      },
                      "technicalContact": [
                        {
                          "firstName": "Werner",
                          "lastName": "Mustermann",
                          "contact": {
                            "telephone": [
                              {
                                "number": "+49 89 32168-42",
                                "mobile": false,
                                "description": "Dienstliches Festnetz"
                              }
                            ]
                          }
                        }
                      ],
                      "callback": {
                        "callbackURI": "https://www.example.com/callback"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          }
        },
        "operationId": "get-destination",
        "description": "Übertragungsziel abfragen",
        "tags": [
          "Destination Management"
        ],
        "security": [
          {
            "OAuth 2.0": [
              "{subscriberId}:destination:read",
              "{subscriberId}:destination:manage",
              "{subscriberId}:manage",
              "{subscriberId}:destination:{destinationId}:read"
            ]
          }
        ]
      },
      "put": {
        "summary": "Update Destination",
        "operationId": "update-destination",
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          }
        },
        "description": "Übertragungsziel aktualisieren",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "../models/destination.json"
              },
              "examples": {
                "example-1": {
                  "value": {
                    "destination-id": "83578",
                    "public-organization": {
                      "organizationName": "Gewerbeamt Musterhausen"
                    },
                    "technicalContact": [
                      {
                        "firstName": "Werner",
                        "lastName": "Mustermann",
                        "contact": {
                          "telephone": [
                            {
                              "number": "+49 89 32168-42",
                              "mobile": false,
                              "description": "Dienstliches Festnetz"
                            }
                          ]
                        }
                      }
                    ],
                    "callback": {
                      "callbackURI": "https://www.example.com/callback"
                    }
                  }
                }
              }
            }
          }
        },
        "tags": [
          "Destination Management"
        ],
        "security": [
          {
            "OAuth 2.0": [
              "{subscriberId}:manage",
              "{subscriberId}:destination:update",
              "{subscriberId}:destination:manage",
              "{subscriberId}:destination:{destinationId}:update"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete Destination",
        "operationId": "delete-destination",
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/error-body.json"
                }
              }
            }
          }
        },
        "description": "Übertragungsziel löschen",
        "tags": [
          "Destination Management"
        ],
        "security": [
          {
            "OAuth 2.0": [
              "{subscriberId}:manage",
              "{subscriberId}:destination:manage",
              "{subscriberId}:destination:delete",
              "{subscriberId}:destination:{destinationId}:delete"
            ]
          }
        ]
      }
    }
  },
  "tags": [
    {
      "name": "Destination Management"
    },
    {
      "name": "Application Retrieval"
    }
  ],
  "components": {
    "securitySchemes": {
      "OAuth 2.0": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://oauth.fiep-poc.de/invoke/pub.apigateway.oauth2/getAccessToken",
            "refreshUrl": "https://oauth.fiep-poc.de/invoke/pub.oauth/refreshAccessToken",
            "scopes": {
              "{subscriberId}:destination:manage": "Dieser Zugriffsbereich alle Destination Endpunkte eines Subscriber genutzt werden.",
              "{subscriberId}:destination:update": "Dieser Zugriffsbereich erlaubt es, bestehende Destinations zu verändern.",
              "{subscriberId}:destination:create": "Der Zugriffsbereich erlaubt Destinations neu anzulegen und zu verändern.",
              "{subscriberId}:destination:read": "Dieser Zugriffsbereich erlaubt bei allen Destination-Informationen ein lesender Zugriff.",
              "{subscriberId}:destination:{destinationId}:read": "Mit diesem Zugriffsbereich wird ein lesender Zugriff auf eine spezifische Destination ermöglicht.",
              "{subscriberId}:application:receive": "Dieser Zugriffsbereich erlaubt es, Anträge für allen Destinations abzuholen.",
              "{subscriberId}:destination:{destinationId}:update": "Mit diesem Zugriffsbereich wird ein schreibende Zugriff auf eine spezifische Destination ermöglicht.",
              "{subscriberId}:manage": "Dieser Zugriffsbereich die vollständige Nutzung aller Endpunkte eines Subscribers.",
              "{subscriberId}:destination:{destinationId}:application:receive": "Dieser Zugriffsbereich erlaubt es, Anträge einer spezifischen Destination abzuholen.",
              "{subscriberId}:destination:{destinationId}:delete": "Dieser Zugriffsbereich erlaubt es, eine spezifische Destination zu löschen.",
              "{subscriberId}:destination:delete": "Dieser Zugriffsbereich erlaubt die Löschung von Destinations eines Accounts."
            }
          }
        },
        "description": "Dieses Authentifizierungsmethode wird genutzt, um den Zugriff auf die Produktiv API zu autorisieren. "
      }
    }
  }
}